#!/usr/bin/python3
# Copyright by HiSilicon Tech. Co. Ltd. 2022
#
# This file reform the log generated by "qemu -d in_asm,exec,nochain" to
# a serial guest instruction.
# usage: reform_exec.py <log>，output to stdout，error to stderr

import sys
import re

if len(sys.argv)!=2:
    sys.stderr.write("usage: " + sys.argv[0] + " <input>\n")
    exit(0)

lines = open(sys.argv[1]).readlines()

INIT = 0
IN_ASM = 1
WITH_KEY = 2
state = INIT

asmblk = {}

p_dash = re.compile(r'----------------')
p_in = re.compile(r'IN:')
p_trace = re.compile(r'Trace ([0-9]+): 0x([0-9a-f]+) \[([0-9a-f]+)/([0-9a-f]+)/([0-9a-f]+)/([0-9a-f]+)\]')
p_disa = re.compile(r'0x([0-9a-f]+):')
p_body = re.compile(r'\(block body\)')
buf = ''
key = 0
line_no = 0

def state_switch(target_state):
    global state
    global key

    # sys.stderr.write("[debug] state switch " + str(state) + " change to " + str(target_state) + " key=" + str(key) + "\n")
    state = target_state

for line in lines:
    if state == INIT:
        if p_dash.match(line):
            state_switch(IN_ASM);
        elif m := p_trace.match(line):
            addr = int(m.group(4), 16)
            sys.stdout.write("------------------------------>\n")
            if addr in asmblk:
                sys.stdout.write(asmblk[addr])
            else:
                sys.stdout.write("(unknown asm on addr " + str(addr) + ")\n")
        else:
            sys.stdout.write(line)
    elif state == IN_ASM:
        if line.strip():
            buf += line
            if m := p_disa.match(line):
                key = int(m.group(1), 16)
                state_switch(WITH_KEY)
            elif p_body.match(line):
                key = -1    # -1 mean this is a worthless body section
                state_switch(WITH_KEY)
        else:
            sys.stderr.write("format error at line " + str(line_no) + ": " + line + "\n")
            state_switch(INIT)
    elif state == WITH_KEY:
        if line.strip():
            buf += line
        else:
            if key in asmblk:
                sys.stderr.write("key " + str(key) + " conflict at line " + str(line_no) + "\n")
            if key != -1:
                asmblk[key] = buf
                state_switch(INIT)
                buf = ''
    else:
        assert False
    line_no += 1
