#!/usr/bin/python3
# Copyright by HiSilicon Tech. Co. Ltd. 2022
#
# This file reform the log generated by "qemu -d in_asm,exec,nochain" to
# a serial guest instruction.
# usage: reform_exec.py <log>，output to stdout，error to stderr

import sys
import re

if len(sys.argv)!=3:
    sys.stderr.write("usage: " + sys.argv[0] + " <stack_file> <system.map>\n")
    exit(0)

sysmap = []
stack = []

def import_map(fname):
    global sysmap
    lines = open(fname).readlines()
    for line in lines:
        if line.startswith('fffffff'):
            addr,t,name = line.split()
            #print("pass ", addr, t, name);
            sysmap.append([int(addr,16), t, name])

def import_stack(fname):
    global stack
    lines = open(fname).readlines()
    for line in lines:
        if line:
            addr,values = line.split(":")
            addr = int(addr, 16)
            values = values.split()
            values.reverse()
            for value in values:
                stack.append([addr, int(value, 16)])
                addr = addr+8

def find_sym(addr):
    if (addr > sysmap[-1][0]) or (addr < sysmap[0][0]):
        return ''

    ret = ''
    for v,t,n in sysmap:
        if addr >= v:
            if addr != v:
                n = n + '+' + str(addr-v)

            T = '(' + t + ')'

            ret = T + n

            if t in "tT":
                ret = ret + '  <-------------'
        else:
            break

    return ret

import_map(sys.argv[2])
import_stack(sys.argv[1])

for v in stack:
    print("%0.16x: %0.16x"%(v[0], v[1]), find_sym(v[1]))
