#!/bin/sh

XQEMU="qemu-linx "
BIN_PATH="bin"

if [ "$(ls ${BIN_PATH})" = "" ];
then
    echo "[\033[31mError\033[0m]\tNothing to do. Run 'make' to generate executable file."
    exit
fi

if [ "$#" -eq 0 ];
then
    for file in "$BIN_PATH"/*
    do
        $XQEMU $file
    done
    exit
fi

for file in "$@"
do
    if [ -e "$BIN_PATH"/"$file" ];
    then
        $XQEMU "$BIN_PATH"/"$file"
    else
        echo "[\033[31mError\033[0m]\tFile not found: '${BIN_PATH}/${file}'."
        echo "    It has not been yet generated, or no corresponding test event exists."
        echo ""
    fi
done
