#ifndef __C_PROTOTYPE_H__
#define __C_PROTOTYPE_H__

extern long blk_addbpc_r(unsigned long a);
extern long blk_addbpc_t(unsigned long a);
extern long blk_addtpc_r(unsigned long a);
extern long blk_addtpc_t(unsigned long a);
extern long blk_add_tt(unsigned long a, unsigned long b);
extern long blk_add_tr(unsigned long a, unsigned long b);
extern long blk_add_rr(unsigned long a, unsigned long b);
extern long blk_addi_r(unsigned long a);
extern long blk_addi_t(unsigned long a);
extern long blk_addiw_r(unsigned long a);
extern long blk_addiw_t(unsigned long a);
extern long blk_addw_tt(unsigned long a, unsigned long b);
extern long blk_addw_tr(unsigned long a, unsigned long b);
extern long blk_addw_rr(unsigned long a, unsigned long b);
extern long blk_and_tt(unsigned long a, unsigned long b);
extern long blk_and_tr(unsigned long a, unsigned long b);
extern long blk_and_rr(unsigned long a, unsigned long b);
extern long blk_andi_r(unsigned long a);
extern long blk_andi_t(unsigned long a);
extern long blk_andiw_r(unsigned long a);
extern long blk_andiw_t(unsigned long a);
extern long blk_andw_tt(unsigned long a, unsigned long b);
extern long blk_andw_tr(unsigned long a, unsigned long b);
extern long blk_andw_rr(unsigned long a, unsigned long b);
extern long blk_bc_tt(unsigned long a, unsigned long b);
extern long blk_bc_tt_1(unsigned long a);
extern long blk_bc_tr(unsigned long a, unsigned long b);
extern long blk_bc_rr(unsigned long a, unsigned long b);
extern long blk_bc_rt(unsigned long a, unsigned long b);
extern long blk_bci_r(unsigned long a, unsigned long b);
extern long blk_bci_t(unsigned long a, unsigned long b);
extern long blk_cmp_eq_tt(unsigned long a, unsigned long b);
extern long blk_cmp_eq_tr(unsigned long a, unsigned long b);
extern long blk_cmp_eq_rr(unsigned long a, unsigned long b);
extern long blk_cmp_eqi_r(unsigned long a);
extern long blk_cmp_eqi_t(unsigned long a);
extern long blk_cmp_ge_tt(unsigned long a, unsigned long b);
extern long blk_cmp_ge_tr(unsigned long a, unsigned long b);
extern long blk_cmp_ge_rr(unsigned long a, unsigned long b);
extern long blk_cmp_ge_rth(unsigned long a, unsigned long b);
extern long blk_cmp_ge_rtl(unsigned long a, unsigned long b);
extern long blk_cmp_gei_r(unsigned long a);
extern long blk_cpm_gei_t(unsigned long a);
extern long blk_cmp_geu_tt(unsigned long a, unsigned long b);
extern long blk_cmp_geu_tr(unsigned long a, unsigned long b);
extern long blk_cmp_geu_rr(unsigned long a, unsigned long b);
extern long blk_cmp_geu_rth(unsigned long a, unsigned long b);
extern long blk_cmp_geu_rtl(unsigned long a, unsigned long b);
extern long blk_cmp_geui_r(unsigned long a);
extern long blk_cmp_geui_t(unsigned long a);
extern long blk_cmp_lt_tt(unsigned long a, unsigned long b);
extern long blk_cmp_lt_tr(unsigned long a, unsigned long b);
extern long blk_cmp_lt_rr(unsigned long a, unsigned long b);
extern long blk_cmp_lt_rth(unsigned long a, unsigned long b);
extern long blk_cmp_lt_rtl(unsigned long a, unsigned long b);
extern long blk_cmp_lti_r(unsigned long a);
extern long blk_cpm_lti_t(unsigned long a);
extern long blk_cmp_ltu_tt(unsigned long a, unsigned long b);
extern long blk_cmp_ltu_tr(unsigned long a, unsigned long b);
extern long blk_cmp_tlu_rr(unsigned long a, unsigned long b);
extern long blk_cmp_ltu_rth(unsigned long a, unsigned long b);
extern long blk_cmp_ltu_rtl(unsigned long a, unsigned long b);
extern long blk_cmp_ltui_r(unsigned long a);
extern long blk_cpm_ltui_t(unsigned long a);
extern long blk_cmp_ne_tt(unsigned long a, unsigned long b);
extern long blk_cmp_ne_tr(unsigned long a, unsigned long b);
extern long blk_cmp_ne_rr(unsigned long a, unsigned long b);
extern long blk_cmp_ne_rth(unsigned long a, unsigned long b);
extern long blk_cmp_ne_rtl(unsigned long a, unsigned long b);
extern long blk_cmp_nei_r(unsigned long a);
extern long blk_cpm_nei_t(unsigned long a);
extern long blk_getw(long a);
extern long blk_j(unsigned long a, unsigned long b);
extern long blk_jr_r(unsigned long a, unsigned long b);
extern long blk_jr_t(unsigned long a, unsigned long b);
extern long blk_or_tt(unsigned long a, unsigned long b);
extern long blk_or_tr(unsigned long a, unsigned long b);
extern long blk_or_rr(unsigned long a, unsigned long b);
extern long blk_ori_r(unsigned long a);
extern long blk_ori_t(unsigned long a);
extern long blk_orw_tt(unsigned long a, unsigned long b);
extern long blk_orw_tr(unsigned long a, unsigned long b);
extern long blk_orw_rr(unsigned long a, unsigned long b);
extern long blk_oriw_r(unsigned long a);
extern long blk_oriw_t(unsigned long a);
extern unsigned long getwu(unsigned long a);
extern long blk_sll_tt(unsigned long a, unsigned long b);
extern long blk_sll_tr(unsigned long a, unsigned long b);
extern long blk_sll_rr(unsigned long a, unsigned long b);
extern long blk_sll_rth(unsigned long a, unsigned long b);
extern long blk_sll_rtl(unsigned long a, unsigned long b);
extern long blk_slli_r(unsigned long a);
extern long blk_slli_t(unsigned long a);
extern long blk_sllw_tt(unsigned long a, unsigned long b);
extern long blk_sllw_tr(unsigned long a, unsigned long b);
extern long blk_sllw_rr(unsigned long a, unsigned long b);
extern long blk_sllw_rth(unsigned long a, unsigned long b);
extern long blk_sllw_rtl(unsigned long a, unsigned long b);
extern long blk_slliw_r(unsigned long a);
extern long blk_slliw_t(unsigned long a);
extern long blk_sra_tt(unsigned long a, unsigned long b);
extern long blk_sra_tr(unsigned long a, unsigned long b);
extern long blk_sra_rr(unsigned long a, unsigned long b);
extern long blk_sra_rth(unsigned long a, unsigned long b);
extern long blk_sra_rtl(unsigned long a, unsigned long b);
extern long blk_srai_r(unsigned long a);
extern long blk_srai_t(unsigned long a);
extern long blk_sraw_tt(unsigned long a, unsigned long b);
extern long blk_sraw_tr(unsigned long a, unsigned long b);
extern long blk_sraw_rr(unsigned long a, unsigned long b);
extern long blk_sraw_rth(unsigned long a, unsigned long b);
extern long blk_sraw_rtl(unsigned long a, unsigned long b);
extern long blk_sraiw_r(unsigned long a);
extern long blk_sraiw_t(unsigned long a);
extern long blk_srl_tt(unsigned long a, unsigned long b);
extern long blk_srl_tr(unsigned long a, unsigned long b);
extern long blk_srl_rr(unsigned long a, unsigned long b);
extern long blk_srl_rth(unsigned long a, unsigned long b);
extern long blk_srl_rtl(unsigned long a, unsigned long b);
extern long blk_srli_r(unsigned long a);
extern long blk_srli_t(unsigned long a);
extern long blk_srlw_tt(unsigned long a, unsigned long b);
extern long blk_srlw_tr(unsigned long a, unsigned long b);
extern long blk_srlw_rr(unsigned long a, unsigned long b);
extern long blk_srlw_rth(unsigned long a, unsigned long b);
extern long blk_srlw_rtl(unsigned long a, unsigned long b);
extern long blk_srliw_r(unsigned long a);
extern long blk_srliw_t(unsigned long a);
extern long blk_subw_tt(unsigned long a, unsigned long b);
extern long blk_subw_tr(unsigned long a, unsigned long b);
extern long blk_subw_rr(unsigned long a, unsigned long b);
extern long blk_subw_rth(unsigned long a, unsigned long b);
extern long blk_subw_rtl(unsigned long a, unsigned long b);
extern long blk_subiw_r(unsigned long a);
extern long blk_subiw_t(unsigned long a);
extern long blk_sub_tt(unsigned long a, unsigned long b);
extern long blk_sub_tr(unsigned long a, unsigned long b);
extern long blk_sub_rr(unsigned long a, unsigned long b);
extern long blk_sub_rth(unsigned long a, unsigned long b);
extern long blk_sub_rtl(unsigned long a, unsigned long b);
extern long blk_subi_r(unsigned long a);
extern long blk_subi_t(unsigned long a);
extern long blk_xorw_tt(unsigned long a, unsigned long b);
extern long blk_xorw_tr(unsigned long a, unsigned long b);
extern long blk_xorw_rr(unsigned long a, unsigned long b);
extern long blk_xorw_rth(unsigned long a, unsigned long b);
extern long blk_xorw_rtl(unsigned long a, unsigned long b);
extern long blk_xoriw_r(unsigned long a);
extern long blk_xoriw_t(unsigned long a);
extern long blk_xor_tt(unsigned long a, unsigned long b);
extern long blk_xor_tr(unsigned long a, unsigned long b);
extern long blk_xor_rr(unsigned long a, unsigned long b);
extern long blk_xor_rth(unsigned long a, unsigned long b);
extern long blk_xor_rtl(unsigned long a, unsigned long b);
extern long blk_xori_r(unsigned long a);
extern long blk_xori_t(unsigned long a);
extern long blk_setc_eq_tt(unsigned long a, unsigned long b);
extern long blk_setc_eq_tr(unsigned long a, unsigned long b);
extern long blk_setc_eq_rr(unsigned long a, unsigned long b);
extern long blk_setc_ne_tt(unsigned long a, unsigned long b);
extern long blk_setc_ne_tr(unsigned long a, unsigned long b);
extern long blk_setc_ne_rr(unsigned long a, unsigned long b);
extern long blk_setc_ge_tt(unsigned long a, unsigned long b);
extern long blk_setc_ge_tr(unsigned long a, unsigned long b);
extern long blk_setc_ge_rr(unsigned long a, unsigned long b);
extern long blk_setc_ge_rtl(unsigned long a, unsigned long b);
extern long blk_setc_ge_rth(unsigned long a, unsigned long b);
extern long blk_setc_geu_tt(unsigned long a, unsigned long b);
extern long blk_setc_geu_tr(unsigned long a, unsigned long b);
extern long blk_setc_geu_rr(unsigned long a, unsigned long b);
extern long blk_setc_geu_rtl(unsigned long a, unsigned long b);
extern long blk_setc_geu_rth(unsigned long a, unsigned long b);
extern long blk_setc_lt_tt(unsigned long a, unsigned long b);
extern long blk_setc_lt_tr(unsigned long a, unsigned long b);
extern long blk_setc_lt_rr(unsigned long a, unsigned long b);
extern long blk_setc_lt_rtl(unsigned long a, unsigned long b);
extern long blk_setc_lt_rth(unsigned long a, unsigned long b);
extern long blk_setc_ltu_tt(unsigned long a, unsigned long b);
extern long blk_setc_ltu_tr(unsigned long a, unsigned long b);
extern long blk_setc_ltu_rr(unsigned long a, unsigned long b);
extern long blk_setc_ltu_rtl(unsigned long a, unsigned long b);
extern long blk_setc_ltu_rth(unsigned long a, unsigned long b);
extern long blk_setc_eqi_r(unsigned long a);
extern long blk_setc_eqi_t(unsigned long a);
extern long blk_setc_nei_r(unsigned long a);
extern long blk_setc_nei_t(unsigned long a);
extern long blk_setc_gei_r(unsigned long a);
extern long blk_setc_gei_t(unsigned long a);
extern long blk_setc_geui_r(unsigned long a);
extern long blk_setc_geui_t(unsigned long a);
extern long blk_setc_lti_r(unsigned long a);
extern long blk_setc_lti_t(unsigned long a);
extern long blk_setc_ltui_r(unsigned long a);
extern long blk_setc_ltui_t(unsigned long a);
extern long blk_cmp_gei_t(unsigned long a);
extern long blk_cmp_lti_t(unsigned long a);
extern long blk_cmp_ltui_t(unsigned long a);
extern long blk_cmp_nei_t(unsigned long a);
extern unsigned long blk_cmp_ltu_rr(unsigned long a, unsigned long b);
extern void blk_sd_rr1(unsigned long *a, unsigned long b);
extern void blk_sw_rr1(unsigned long *a, unsigned long b);
extern void blk_sd_rr0(unsigned long *a, unsigned long b);
extern void blk_sw_rr0(unsigned long *a, unsigned long b);
extern void blk_sd_t(unsigned long *a, unsigned long b);
extern void blk_sd_db(unsigned long *a, unsigned long b);
extern void blk_sw_bd(unsigned long *a, unsigned long b);
extern void blk_sd_bd(unsigned long *a, unsigned long b);
extern void blk_sw_db(unsigned long *a, unsigned long b);
extern void blk_sd_sp_t(unsigned long *a, unsigned long b);
extern void blk_sw_sp_t(unsigned long *a, unsigned long b);
extern void blk_sd_sp_r(unsigned long *a, unsigned long b);
extern void blk_sw_sp_r(unsigned long *a, unsigned long b);
extern unsigned long blk_sh_t(unsigned long *a, unsigned long b);
extern void blk_sw_t(unsigned long *a, unsigned long b);
extern void blk_sb_t(unsigned long *a, unsigned long b);
extern int blk_lwu_ip(void);
extern int blk_lw_ip(void);
extern long blk_ld_ip(void);
extern long blk_lb_sp(long *a);
extern long blk_lbu_sp(unsigned long *a);
extern void blk_sb_sp(unsigned long *a, unsigned long b);
extern unsigned long blk_ld_sp(unsigned long *a);
extern void blk_sd_sp(unsigned long *a, unsigned long b);
extern long blk_lh_sp(long *a);
extern long blk_lhu_sp(unsigned long *a);
extern void blk_sh_sp(unsigned long *a, unsigned long b);
extern long blk_lw_sp(long *a);
extern long blk_lwu_sp(unsigned long *a);
extern unsigned long blk_lwu_r(unsigned long *a);
extern unsigned long blk_lhu_r(unsigned long *a);
extern unsigned long blk_lbu_r(unsigned long *a);
extern long blk_ld_r(unsigned long *a);
extern long blk_lw_r(unsigned long *a);
extern long blk_lh_r(unsigned long *a);
extern long blk_lb_r(unsigned long *a);
extern long blk_ld_t(unsigned long *a);
extern long blk_lw_t(unsigned long *a);
extern long blk_lh_t(unsigned long *a);
extern long blk_lb_t(unsigned long *a);
extern long blk_lwu_t(unsigned long *a);
extern long blk_lhu_t(unsigned long *a);
extern long blk_lbu_t(unsigned long *a);
extern long blk_mul(unsigned long a, unsigned long b);
extern long blk_mulh(unsigned long a, unsigned long b);
extern long blk_mulhu(unsigned long a, unsigned long b);
extern long blk_mulhsu(unsigned long a, unsigned long b);
extern long blk_mulw(unsigned long a, unsigned long b);
extern long blk_div(unsigned long a, unsigned long b);
extern long blk_divu(unsigned long a, unsigned long b);
extern long blk_divw(unsigned long a, unsigned long b);
extern long blk_divuw(unsigned long a, unsigned long b);
extern long blk_rem(unsigned long a, unsigned long b);
extern long blk_remu(unsigned long a, unsigned long b);
extern long blk_remw(unsigned long a, unsigned long b);
extern long blk_remuw(unsigned long a, unsigned long b);
extern long blk_rev8(unsigned long a);
extern long blk_rev16(unsigned long a);
extern long blk_rev32(unsigned long a);
extern long blk_ag_tw_a(unsigned long a, unsigned long b);
extern long blk_ag_tw0_b(unsigned long a, unsigned long b);
extern long blk_ag_tw1_b(unsigned long a, unsigned long b);
extern long blk_ag_tw_d(unsigned long a, unsigned long b);
extern long blk_ag_uxtw_a(unsigned long a, unsigned long b);
extern long blk_ag_uxtw_b(unsigned long a, unsigned long b);
extern long blk_ag_uxtw_c(unsigned long a, unsigned long b);
extern long blk_ag_uxtw_d(unsigned long a, unsigned long b);
extern long blk_ag_uxtd_a(unsigned long a, unsigned long b);
extern long blk_ag_uxtd_b(unsigned long a, unsigned long b);
extern long blk_ag_uxtd_c(unsigned long a, unsigned long b);
extern long blk_ag_uxtd_d(unsigned long a, unsigned long b);
extern long blk_ag_sxtw_a(unsigned long a, unsigned long b);
extern long blk_ag_sxtw_b(unsigned long a, unsigned long b);
extern long blk_ag_sxtw_c(unsigned long a, unsigned long b);
extern long blk_ag_sxtw_d(unsigned long a, unsigned long b);
extern long blk_ag_sxtd_a(unsigned long a, unsigned long b);
extern long blk_ag_sxtd_b(unsigned long a, unsigned long b);
extern long blk_ag_sxtd_c(unsigned long a, unsigned long b);
extern long blk_ag_sxtd_d(unsigned long a, unsigned long b);
extern long blk_ag_td_a(unsigned long a, unsigned long b);
extern long blk_ag_td0_b(unsigned long a, unsigned long b);
extern long blk_ag_td1_b(unsigned long a, unsigned long b);
extern long blk_ag_td_d(unsigned long a, unsigned long b);
extern long blk_bxu(unsigned long a, unsigned long b);
extern long blk_bxs(unsigned long a, unsigned long b);
extern long blk_bmg(unsigned long a, unsigned long b);
extern long blk_bam(unsigned long a, unsigned long b);
#endif

